from __future__ import annotations

from typing import Any

_BIND_NAMES = ('_CODEX_HOT_PATH_PROFILE', '_HOT_PATH_AUTO_ESCALATION_ARCHITECTURE_FAMILIES', '_HOT_PATH_AUTO_ESCALATION_CONSERVATIVE_FAMILIES', '_HOT_PATH_AUTO_SESSION_BRIEF_FAMILIES', '_HOT_PATH_SUMMARY_ONLY_FALLBACK_FAMILIES', '_PROCESS_ARCHITECTURE_PACKET_CACHE', '_architecture_bundle_mermaid_signature_hash', '_bootstrap_record_path', '_bootstrap_relevant_docs', '_broad_shared_only_input', '_compact_bootstrap_workstream_selection', '_compact_component_row_for_packet', '_compact_context_dossier', '_compact_diagram_row_for_packet', '_compact_engineering_notes', '_compact_hot_path_payload_within_budget', '_compact_hot_path_runtime_packet', '_compact_miss_recovery_for_packet', '_compact_packet_level_architecture_audit', '_compact_runtime_timing_rows_for_packet', '_compact_stage_timings', '_compact_test_row_for_packet', '_compact_truncation_for_summary', '_compact_workstream_reference_for_packet', '_compact_workstream_row_for_packet', '_compact_workstream_selection_for_packet', '_companion_context_paths', '_connect', '_decode_compact_selected_counts', '_decode_hot_path_execution_profile', '_dedupe_strings', '_delivery_profile_hot_path', '_elapsed_stage_ms', '_fallback_scan_payload', '_full_scan_guidance', '_git_branch_name', '_git_head_oid', '_governance_closeout_doc_count', '_hot_path_auto_escalation_trigger', '_hot_path_can_hold_local_narrowing_without_full_scan', '_hot_path_execution_profile_runtime_fields', '_hot_path_full_scan_reason', '_hot_path_full_scan_recommended', '_hot_path_governance_obligations', '_hot_path_packet_rank', '_hot_path_payload_is_compact', '_hot_path_route_ready', '_hot_path_routing_confidence', '_hot_path_synthesized_execution_profile', '_hot_path_validation_bundle', '_hot_path_workstream_selection', '_impact_packet_state', '_impact_summary_payload', '_load_judgment_workstream_hint', '_local_runtime_execution_summary', '_normalize_claim_mode', '_normalize_family_hint', '_normalized_string_list', '_packet_benchmark_summary_for_runtime_packet', '_payload_packet_kind', '_payload_workstream_hint', '_projection_cache_signature', '_repo_scan_degraded_reason', '_resolve_changed_path_scope_context', '_session_conflicts', '_should_escalate_hot_path_to_session_brief', '_update_compact_hot_path_runtime_packet', '_utc_now', '_validation_bundle_command_count', '_warm_runtime', '_workstream_selection', 'build_impact_report', 'list_session_states', 'load_context_dossier', 'load_runtime_optimization_snapshot', 'load_runtime_timing_summary', 'odylith_architecture_mode', 'odylith_context_cache', 'odylith_evaluation_ledger', 'prune_runtime_records', 'read_runtime_state', 'record_runtime_timing', 'register_session_state', 'request_runtime_daemon', 'routing', 'tooling_context_packet_builder', 'tooling_guidance_catalog')

def bind_packet_runtime(target_globals: dict[str, Any], host: Any) -> None:
    getter = host.__getitem__ if isinstance(host, dict) else lambda name: getattr(host, name)
    for name in _BIND_NAMES:
        try:
            target_globals[name] = getter(name)
        except (AttributeError, KeyError):
            continue
