"""Vocabulary constants for greenfield component artifact extraction."""

from __future__ import annotations

ACTION_VERBS = (
    "accept", "add", "adjust", "allocate", "apply", "approve", "assemble", "assign", "attach", "block", "build", "calculate", "capture",
    "check", "choose", "combine", "compare", "complete", "compute", "connect", "convert", "correlate", "create", "decide", "delete", "derive",
    "describe", "display", "draft", "edit", "enter", "estimate", "explain", "export", "find", "grant", "group", "guide", "handoff", "handle",
    "drill", "forecast", "flag", "highlight", "import", "include", "inspect", "issue", "keep", "land", "link", "leave", "log", "make", "maintain",
    "manage", "normalize", "notify", "open", "optimize", "order", "move", "pair", "persist", "pick", "predict", "present",
    "prepare", "propose", "provide", "produce", "publish", "pull", "rank", "read", "receive", "recommend", "record", "render", "request",
    "reach", "recompute", "resolve", "respond", "review", "route", "run", "save", "schedule", "score", "see", "select", "send", "set", "settle", "show", "store",
    "submit", "suggest", "summarize", "sync", "track", "update", "upload", "validate", "verify", "view", "watch",
)

GENERIC_TERMS = {
    "accepted",
    "actor",
    "application",
    "boundary",
    "both",
    "candidate",
    "component",
    "contract",
    "domain",
    "evidence",
    "explicit",
    "explicitly",
    "first",
    "greenfield",
    "hand",
    "handoff",
    "help",
    "input",
    "later",
    "least",
    "local",
    "only",
    "off",
    "output",
    "path",
    "planned",
    "product",
    "project",
    "proof",
    "record",
    "release",
    "reviewer",
    "service",
    "single",
    "source",
    "state", "such",
    "system",
    "validation",
    "made",
    "mistake",
    "person",
    "proven",
    "succeed",
    "success",
    "their",
    "they",
    "today",
    "with",
    "what",
    "whether",
    "working",
    "from", "into", "as",
    "then", "through", "your",
}

ARTIFACT_CARRIER_TERMS = {
    "alternative", "alternatives",
    "answer", "answers",
    "assignment", "assignments",
    "blocker", "blockers",
    "blocking",
    "confirmation", "confirmations",
    "contact", "contacts",
    "criteria", "channel", "channels", "context", "data",
    "decision",
    "description",
    "descriptions",
    "detail",
    "details",
    "evidence",
    "event",
    "events",
    "field",
    "fields",
    "flag",
    "flags",
    "form",
    "forms",
    "guardrail",
    "guardrails",
    "history",
    "input",
    "inputs",
    "intake",
    "journal",
    "journals",
    "ledger",
    "list",
    "lists",
    "log",
    "logs",
    "marker",
    "markers",
    "metric",
    "metrics",
    "measurement",
    "note",
    "notes",
    "outcome",
    "outcomes",
    "output",
    "outputs",
    "option",
    "options",
    "package",
    "packet",
    "preference",
    "preferences",
    "profile",
    "profiles",
    "readiness",
    "recommendation",
    "recommendations",
    "rationale",
    "record",
    "records",
    "request",
    "result",
    "review",
    "reviews",
    "rule",
    "rubric",
    "rubrics",
    "score",
    "signal",
    "state",
    "status",
    "store",
    "stores",
    "suggestion",
    "suggestions",
    "summary",
    "timeline",
    "tracking",
    "unit",
    "units",
    "version",
    "versioning",
    "view",
    "visit",
    "visits",
}


__all__ = ["ACTION_VERBS", "ARTIFACT_CARRIER_TERMS", "GENERIC_TERMS"]
